# Basic Configuration
baseURL = "http://localhost:1313/blog"  # Local development URL
languageCode = "en-us"
title = "0xo3o"
theme = "PaperMod"

# Content and Output
contentDir = "content-blog"
publishDir = "public/blog"
enableRobotsTXT = true
canonifyURLs = false

# Theme Parameters
[params]
  env = "development"  # This replaces HUGO_ENV
  defaultTheme = "auto"
  
  # Profile Mode
  [params.profileMode]
    enabled = true
    title = "0xo3o"  # that's exactly what i need.
    subtitle = "Welcome to my blog!"
    imageUrl = "/blog/img/profile.jpg"
    imageTitle = "my picture"
    imageWidth = 150     # Default size matching desktop CSS
    imageHeight = 150
    imageClass = "img-circle"
    buttons = [
      { name = "Posts", url = "posts" },
      { name = "About Me", url = "about" },
      { name = "Tags", url = "tags" }
    ]

  # UI Settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  # Asset Settings
  [params.assets]
    disableScrollBarStyle = true
    disableFingerprinting = true

# Main Menu Items
[[menu.main]]
  identifier = "about"
  name = "About Me"
  url = "/blog/about/"
  weight = 10

[[menu.main]]
  identifier = "tech"
  name = "Tech"
  url = "/blog/categories/tech/"
  weight = 20

[[menu.main]]
  identifier = "life"
  name = "Life"
  url = "/categories/life/"
  weight = 30

[[menu.main]]
  identifier = "tutorials"
  name = "Tutorials"
  url = "/categories/tutorials/"
  weight = 40

# 修改資源處理部分
[[module.mounts]]
source = "themes/PaperMod/assets"
target = "assets"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static"
target = "static"

# 確保資源正確處理
[build]
  writeStats = true
  [[build.mounts]]
    source = "themes/PaperMod/assets"
    target = "static/assets"

# Add this section to handle the root URL redirect
[outputs]
  home = ["HTML", "RSS", "JSON", "REDIRECTS"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    delimiter = ""
    suffixes = [""]

[outputFormats]
  [outputFormats.REDIRECTS]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[[redirects]]
  from = "/"
  to = "/blog/"
  status = 301
  force = true

[deployment]
  [[deployment.targets]]
    name = "production"
    URL = "https://0xo3o.com/blog"

  [[deployment.matchers]]
    pattern = "^HUGO_ENV=production$"
    URL = "https://0xo3o.com/blog"
  