# Basic Configuration
baseURL = "http://localhost:1313"
languageCode = "en-us"
enableRobotsTXT = true
canonifyURLs = false
theme = "PaperMod"

# Content and Output Configuration
[module]
  [[module.mounts]]
    source = "content/blog"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "themes/PaperMod/assets"
    target = "assets"
  [[module.mounts]]
    source = "assets"
    target = "assets"

# Theme-specific configurations
[params]
  env = "development"
  defaultTheme = "auto"
  
  # Profile Mode
  [params.profileMode]
    enabled = true
    title = "0xo3o"
    subtitle = "Welcome to my blog!"
    imageUrl = "/img/profile.jpg"
    imageTitle = "my picture"
    imageWidth = 150
    imageHeight = 150
    imageClass = "img-circle"
    buttons = [
      { name = "Posts", url = "posts" },
      { name = "About Me", url = "about" },
      { name = "Tags", url = "tags" }
    ]

  # UI Settings (Added from blog-config)
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  # Asset Settings
  [params.assets]
    disableScrollBarStyle = true
    disableFingerprinting = true
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

# Main Menu Items (Added from blog-config)
[[menu.main]]
  identifier = "about"
  name = "About Me"
  url = "/blog/about/"
  weight = 10

[[menu.main]]
  identifier = "tech"
  name = "Tech"
  url = "/blog/categories/tech/"
  weight = 20

[[menu.main]]
  identifier = "life"
  name = "Life"
  url = "/blog/categories/life/"
  weight = 30

[[menu.main]]
  identifier = "tutorials"
  name = "Tutorials"
  url = "/blog/categories/tutorials/"
  weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"] 