baseURL = "http://localhost:1313/terminal"  # Local development URL
languageCode = "en-us"
title = "Terminal CV"
theme = "terminalcv"
contentDir = "content-terminal"
publishDir = "public/terminal"
enableRobotsTXT = true
canonifyURLs = false

