# Basic Configuration
baseURL = "http://localhost:1313/terminal"
theme = "terminalcv"
contentDir = "content/terminal"
publishDir = "public/terminal"

[module]
  [[module.mounts]]
    source = "content/terminal"
    target = "content"

